# Generated by Django 5.1.3 on 2025-11-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0006_city_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=125),
        ),
    ]
