

server {
    listen 80;
    server_name touristguide.work www.touristguide.work;

    client_max_body_size 20M;

    location /api/ {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /media/ {
        alias /app/media/;
   }


    location / {
        proxy_pass http://frontend:80/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

location /secure-management-3228js9/ {				
	proxy_pass http://backend:8000/secure-management-3228js9/;			
	proxy_set_header Host $host;			
	proxy_set_header X-Real-IP $remote_addr;			
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;			
	proxy_set_header X-Forwarded-Proto $scheme;			
	}	


location /activate/ {
    proxy_pass http://frontend:80/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
}





location /reset-password/ {
    proxy_pass http://frontend:80/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;


}
}
